cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/restful-spring
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

springdoc:
  swagger-ui:
    use-root-path: true
